### ISSUE TITLE
Issue when install on ubuntu

### ISSUE THREAD

**Issue by cooleye72** [aiverify-foundation/moonshot#240]
Hi, 

I am trying to install moonshot on ubuntu machine and have met the prerequisites 

![image](https://github.com/aiverify-foundation/moonshot/assets/62092752/8c18f473-49df-441e-82f6-3accb2df7c27)
![image](https://github.com/aiverify-foundation/moonshot/assets/62092752/5935ee66-4641-4d94-ade8-d4741ebba75f)

I encountered the following error when trying to install moonshot. Can you advise?
![image](https://github.com/aiverify-foundation/moonshot/assets/62092752/b09bb163-3117-4ff5-b544-f363fcd44f7c)

**Comment by imda-normanchia** [comment]
hello, thanks for trying out moonshot. 

may i know what is the pip version that you are running? you can check by running `pip3 --version`

**Comment by cooleye72** [comment]
Hi,

below is the pip version
pip3 --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by cooleye72** [comment]
I know where the issue is. The pip3 is still the old version. link to python 3.11 and it is able to install now. Thanks
![image](https://github.com/aiverify-foundation/moonshot/assets/62092752/74f6405f-2208-4358-b3e3-f35f73c6954a)

**Comment by cooleye72** [comment]
tried to install the moon ui and noticed it is unable to retrieve the environment variables. Is it the correct behavior?
![image](https://github.com/aiverify-foundation/moonshot/assets/62092752/ce08be9c-52f2-43a0-a90c-1b0cf5a215fa)

**Comment by imda-normanchia** [comment]
can you try running `cat .env` to ensure that this configuration file was created. 

if you see a value similar to this `cat: .env: No such file or directory` . can you try deleting moonshot-data folder and run `python -m moonshot -i moonshot-data` again. 

else if there is value printed out similar to the codeblock below, try running `python -m moonshot web` to see if the same error appear. 
```
    ATTACK_MODULES="../moonshot-data/attack-modules"
    CONNECTORS="../moonshot-data/connectors"
    CONNECTORS_ENDPOINTS="../moonshot-data/connectors-endpoints"
    CONTEXT_STRATEGY="../moonshot-data/context-strategy"
    COOKBOOKS="../moonshot-data/cookbooks"
    DATABASES="../moonshot-data/generated-outputs/databases"
    DATABASES_MODULES="../moonshot-data/databases-modules"
    DATASETS="../moonshot-data/datasets"
    IO_MODULES="../moonshot-data/io-modules"
    METRICS="../moonshot-data/metrics"
    ...
```

**Comment by cooleye72** [comment]
I ran into issue on installing h5py package when run `python -m moonshot -i moonshot-data `. I am using ubuntu VM on Mac ARM machine. Is there anyway to install h5py on ubuntu ARM?

![image](https://github.com/aiverify-foundation/moonshot/assets/62092752/f5bc0a23-8381-4adc-854a-9f49efd1a257)

**Comment by imda-normanchia** [comment]
may I know which Macbook version are you using,which cpu? and if it's possible to copy paste the full error code as it is difficult to determine the issue based on the snippet above. 

alternatively if you are able to install the h5py separately, do create a `.env` file in the folder that you are running moonshot to point to the moonshot-data repository. an example of how the .env file should look like is as below. 

```
	 ATTACK_MODULES="./moonshot-data/attack-modules"
    CONNECTORS="./moonshot-data/connectors"
    CONNECTORS_ENDPOINTS="./moonshot-data/connectors-endpoints"
    CONTEXT_STRATEGY="./moonshot-data/context-strategy"
    COOKBOOKS="./moonshot-data/cookbooks"
    DATABASES="./moonshot-data/generated-outputs/databases"
    DATABASES_MODULES="./moonshot-data/databases-modules"
    DATASETS="./moonshot-data/datasets"
    IO_MODULES="./moonshot-data/io-modules"
    METRICS="./moonshot-data/metrics"
    PROMPT_TEMPLATES="./moonshot-data/prompt-templates"
    RECIPES="./moonshot-data/recipes"
    RESULTS="./moonshot-data/generated-outputs/results"
    RESULTS_MODULES="./moonshot-data/results-modules"
    RUNNERS="./moonshot-data/generated-outputs/runners"
    RUNNERS_MODULES="./moonshot-data/runners-modules"
    TOKENIZERS_PARALLELISM = false 
   
    # For Web API
    HOST_ADDRESS=127.0.0.1 # The interface the server will bind to
    HOST_PORT=5000

    # Below is the uri of the Web UI webhook.
    # In the next section, if Web UI listens on a different port,
    # update this uri accordingly and restart.

    MOONSHOT_UI_CALLBACK_URL=http://localhost:3000/api/v1/benchmarks/status
```

**Comment by cooleye72** [comment]
I am using MacBook Pro, CPU is Apple M2 Pro. Running Ubuntu Virtual VM to install moonshot. Any compatibility issue?

**Comment by imda-normanchia** [comment]
While we haven't specifically tested the application in an Ubuntu VM environment on Mac OS, we can't definitively speak to any compatibility issues. We recommend that you install the version of h5py that aligns with your machine's specifications and try running moonshot again. Also, ensure to create the .env configuration file as illustrated above.

**Comment by imda-normanchia** [comment]
hello, would like to follow up and check if you are still having difficulty starting up moonshot. if there is no issue, I will be closing this issue.

**Comment by cooleye72** [comment]
I still couldnt get it working even I create the .env folder. I guess most probably is due to h5py not compatible with M2 chip. If you manage to test ubuntu on M2 chip, please share with me the steps. Thanks!

**Comment by imda-normanchia** [comment]
According to the error message that you have posted, it seems that you are facing an error with the installation of this 2 package `mpi4py` and `h5py`. What you can do is that maybe you can try to install this 2 requirement separately on your own and try to run moonshot.
