### ISSUE TITLE
Install fail for x86 MacOS (Dependency Torch@2.3.0 pip binaries not available)

### ISSUE THREAD

**Issue by chiraag-imda** [aiverify-foundation/moonshot#241]
`python -m moonshot i moonshot-data` fails on x86 MacOS because `moonshot-data/requirements.txt` contains hard reference `torch==2.3.0`. Would suggest following options for mac silicon transition phase until [5 June 2028](https://en.wikipedia.org/wiki/Mac_transition_to_Apple_silicon#:~:text=June%205%2C%202028%3A%20Intel%20hardware%20will%20reach%20%22vintage%22%20status%20after%20having%20been%20discontinued%20five%20years%20prior%2C%20ending%20most%20of%20Apple%27s%20service%20and%20parts%20support%20for%20Intel%20hardware.):
- documenting alternative instructions for installation for x86 MacOS users 
- relaxing the requirements to `torch>=2.2.0,<=2.3.0` since `2.3.0` features are not currently utilized and no apparent conflicts

[Link](https://github.com/pytorch/pytorch/issues/114602) to relevant PyTorch issue

Error Message:  
<img width="452" alt="image" src="https://github.com/aiverify-foundation/moonshot/assets/172353400/5fa1dc76-d9c1-4041-887f-26423dc37e33">

**Comment by imda-normanchia** [comment]
Thank you for bringing this issue to our attention. While we acknowlege this concern and will document it accordingly, we regret to inform you that we do not have plans to support older MacBooks. A quick solution to this would be advising to manually install the older version for now.

We will continue work on providing an alternative solution for users affected by this issue.

If you encounter an error while installing moonshot-data, it's possible that your configuration file may not be created automatically. In such a case, you will need to manually create a `.env` file. Here's an example of what the content of this file might look like:

```
# For Data
    ATTACK_MODULES="../moonshot-data/attack-modules"
    CONNECTORS="../moonshot-data/connectors"
    CONNECTORS_ENDPOINTS="../moonshot-data/connectors-endpoints"
    CONTEXT_STRATEGY="../moonshot-data/context-strategy"
    COOKBOOKS="../moonshot-data/cookbooks"
    DATABASES="../moonshot-data/generated-outputs/databases"
    DATABASES_MODULES="../moonshot-data/databases-modules"
    DATASETS="../moonshot-data/datasets"
    IO_MODULES="../moonshot-data/io-modules"
    METRICS="../moonshot-data/metrics"
    PROMPT_TEMPLATES="../moonshot-data/prompt-templates"
    RECIPES="../moonshot-data/recipes"
    RESULTS="../moonshot-data/generated-outputs/results"
    RESULTS_MODULES="../moonshot-data/results-modules"
    RUNNERS="../moonshot-data/generated-outputs/runners"
    RUNNERS_MODULES="../moonshot-data/runners-modules"
    TOKENIZERS_PARALLELISM = false

    # For Web API
    HOST_ADDRESS=127.0.0.1 # The interface the server will bind to
    HOST_PORT=5000

    # Below is the uri of the Web UI webhook.
    # In the next section, if Web UI listens on a different port,
    # update this uri accordingly and restart.

    MOONSHOT_UI_CALLBACK_URL=http://localhost:3000/api/v1/benchmarks/status%
```
