### ISSUE TITLE
[Potential Bug] Unable to create a new session in CLI

### ISSUE THREAD

**Issue by imda-lseokmin** [aiverify-foundation/moonshot#261]
### Description

I was unable to create a new red teaming session on CLI. The error message is shown as follow:

```
moonshot > new_session rt_test_chinese123 -e "['openai-gpt4']"
Established connection to database (../moonshot-data/generated-outputs/databases/rt-test-chinese123.db)
[Session] Creating new session.
[Runner] Failed to load runner: [Runner] Unable to load runner because the runner file does not exist.
EXCEPTION of type 'RuntimeError' occurred with message: [Runner] Unable to load runner because the runner file does not exist.
To enable full traceback, run the following command: 'set debug true'
moonshot >
```

#### Workaround

For now, there is a workaround as the runner file `rt_test_chinese123` is successfully created in the designated folder. I can load the session again using `new_session rt_test_chinese123`

### Steps to Reproduce

1. Run moonshot in CLI version - `python -m moonshot cli interactive`
2. Create a new red teaming session - `moonshot > new_session new_session123 -e "['openai_gpt4']"`

**Comment by imda-benedictlee** [comment]
Issue Fixed. Screenshot attached.
<img width="1363" alt="Screenshot 2024-07-16 at 5 35 33 PM" src="https://github.com/user-attachments/assets/c232ce34-12ad-4b74-a4b1-e7cf179820a1">

**Comment by imda-benedictlee** [comment]
Issue has been resolved.
