### ISSUE TITLE
[Potential Bug] Unable to "View Past Runs" in Web UI

### ISSUE THREAD

**Issue by JCoder03** [aiverify-foundation/moonshot#274]
**Description**

I am unable to view the past benchmarking runs on the Web UI, as I get the error message that "n is undefined" when I click on "View Past Runs".

```
[2024-07-29 16:00:20,401] [INFO] [moonshot.integrations.web_api.app]: Request origin: None

2024-07-29 16:00:20,428 [ERROR][result.py::get_available_items(122)] Failed to get available results: Expecting value: line 33 column 31 (char 819)
```

**Comment by imda-benedictlee** [comment]
Hi @JCoder03, can you help me by providing screenshots of the issue that you are facing? Also, may I know if this is a one time occurrence or this happens often?

**Comment by JCoder03** [comment]
This bug happens everytime I click on "View Past Runs":
<img width="958" alt="Bug1" src="https://github.com/user-attachments/assets/9d47d4a9-b525-4918-b60d-2a06d09fa888">

**Comment by imda-benedictlee** [comment]
Hi @JCoder03, I am unable to replicate the issue. Will take a look.

**Comment by miyamaya9** [comment]
@JCoder03 hi, may I know if you are still experiencing this after our latest version. If you are still have problem, could you provide more information of your set up and the steps that triggered this error? (E.g. tried testing xxx cookbook, click on xx and expected to see xxx but got shown xxx error) thank you!

**Comment by JCoder03** [comment]
Hi, upon reinstalling Moonshot from scratch, I did not face this error anymore.
