### ISSUE TITLE
Why is it asking TOGETHER_API_KEY without together? 

### ISSUE THREAD

**Issue by parolkar** [aiverify-foundation/moonshot#287]
Hi All, 
  I just did a fresh install and wanted to test against my local model. The test ran on but ended up with this error on the moonshot UI.
  
  
<img width="340" alt="Screenshot 2024-08-02 at 7 20 55 PM" src="https://github.com/user-attachments/assets/c465dc5d-93c7-4d9a-9300-b475d34071d6">

I have nothing to do with togetherai on this project, is there a specific dependency / requirement for running benchmarks?

**Comment by parolkar** [comment]
Just to let you know , I resolved this by setting the key in my environment but unsure why is it depending on TogetherAI key and should it be specified in the documentation?

**Comment by fcanogab** [comment]
The same just happened to me using the cli. The error is the same. It happened to me after the evaluation finished, after 33 hours of execution. I think it should not be a requirement or there should be an alternative.

**Comment by imda-kelvinkok** [comment]
Hi @parolkar. Thank you for raising this issue.

Can I know which benchmark test you were running? You can see the requirements of our benchmark tests and red teaming modules here: https://aiverify-foundation.github.io/moonshot/faq/ under 'My tests are all completed with errors! I can't view any report!'.  If you do not have a together API token, you can follow the steps to replace the required endpoint with your desired endpoint.

We understand that this is a problem as the requirements for running a test are not shown to users. This is something we will be working on in the next few weeks.

**Comment by imda-kelvinkok** [comment]
@fcanogab. Thank you for your feedback.

I am sorry that happened. We are working on flashing the requirements to users prior to running tests so that this will not happen again. In the meanwhile, you can check out  https://aiverify-foundation.github.io/moonshot/faq/ under 'My tests are all completed with errors! I can't view any report!' for the list of requirements.

**Comment by parolkar** [comment]
Hi Kelvin, I was using MLCommons, yes I think your link here explains the cause. Thanks!
