### ISSUE TITLE
Broken link for troubleshooting installation

### ISSUE THREAD

**Issue by gang-yi** [aiverify-foundation/moonshot#332]
Hi,

the link to the troubleshooting guide in the readme appears to be broken - https://aiverify-foundation.github.io/moonshot/common_issues/

![image](https://github.com/user-attachments/assets/7627b967-42c3-4456-92cd-9bebcd73b0e8)

**Comment by imda-normanchia** [comment]
hello, thanks for bringing up this issue. we are aware and have already made a fix for this issue which we will be merging it soon.
do refer to this link for the troubleshooting guides instead. https://aiverify-foundation.github.io/moonshot/faq/
