### ISSUE TITLE
aiverify-moonshot 0.4.6 requires datasets==2.20.0, but you have datasets 2.14.4 which is incompatible.

### ISSUE THREAD

**Issue by manganganath** [aiverify-foundation/moonshot#333]
Even after uninstalling datasets 2.14.4, still gets the same error

**Comment by imda-normanchia** [comment]
may i know what version of python and pip you are running at?

**Comment by manganganath** [comment]
Python 3.11 and pip 24.2

**Comment by imda-normanchia** [comment]
i am unable to replicate the issue on my end even tho i am running the same python and pip version as you. can you try reinstalling this in a new virtual environment?

**Comment by manganganath** [comment]
That worked. Thanks.

**Comment by imda-normanchia** [comment]
that's great.i will be closing this issue now. thank you.
